import { faker } from '@faker-js/faker'
import { collection, getDocs, orderBy, query } from 'firebase/firestore'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { useRecoilState } from 'recoil'
import { postsState } from '../atoms/postsAtom'
import { suggestionsState } from '../atoms/suggestionsAtom'
import { Feed } from '../components/Feed'
import { Header } from '../components/Header'
import { Modal } from '../components/Modal'
import { db } from '../firebase'

const Home: NextPage = ({ fakePosts, posts, suggestionsData }: any) => {
  const [, setSuggestions] = useRecoilState(suggestionsState)
  const [, setPosts] = useRecoilState(postsState)

  useEffect(() => {
    setSuggestions(suggestionsData)
    setPosts({ fakePosts, posts })
  }, [])

  return (
    <div className='bg-gray-50 h-screen overflow-y-scroll scrollbar-hide'>
      <Head>
        <title>Insta Like</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <Feed />

      <Modal />
    </div>
  )
}

export async function getStaticProps() {
  const suggestionsData = [...Array(20)].map(() => ({
    address: faker.address.street(),
    avatar: faker.image.avatar(),
    birthdate: faker.date.birthdate().toString(),
    company: faker.company.name(),
    email: faker.internet.email(),
    id: faker.datatype.uuid(),
    name: faker.name.firstName(),
    password: faker.internet.password(),
    username: faker.internet.userName(),
  }))

  const fakePosts = [...Array(10)].map(() => {
    return {
      caption: faker.lorem.sentence(),
      id: faker.datatype.uuid(),
      image: faker.image.nature(500, 500, true),
      profileImg: faker.image.avatar(),
      username: faker.internet.userName(),
    }
  })

  const postsSnapShot = await getDocs(
    query(collection(db, 'posts'), orderBy('timestamp', 'desc'))
  )

  return {
    props: {
      fakePosts,
      posts: postsSnapShot.docs,
      suggestionsData,
    },
  }
}

export default Home
