import type { NextPage } from 'next'
import Head from 'next/head'

import { Header } from '../components/Header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Insta Like</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Insta Like</h1>

      {/* header */}
      <Header />

      {/* feed */}

      {/* modal */}
    </div>
  )
}

export default Home
